name: Deploy Multi-Env

on:
  push:
    branches:
      - main
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes
        run: npm test

      - name: Deploy PRODUÇÃO
        if: github.ref == 'refs/heads/main'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_PROD }}

      - name: Deploy TESTE
        if: github.ref == 'refs/heads/test'
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_TEST }}
